### ISSUE TITLE
non-copyleft license non-practical

### ISSUE THREAD

**Issue by andreygursky** [dtromb/gogsl#12]
> To say hello, or for a non-copyleft license, please contact me at dave.trombley@gmail.com. I'd love to know who you are and what you're using gogsl for!

Of course, you could give a non-copyleft license for your go code, but since the libgsl itself remains GPL, this doesn't make sense to have a non-GPL binding. Or I'm missing something?

**Comment by dtromb** [comment]
I generally leave a statement like that in my licenses/documentation like this to let potential clients/employers know that there are options for using the software commercially, when these exist.    

In this case, you're right - the code couldn't be used in a non-GPL way simply run/linked as intended. 

 There are of course other reasons bits of code get licensed (this was originally supposed to be a generic/general C-library wrapper), and of course the whole link clause argument comes into play here...  but it strikes me that there is a) only a small chance of the happening, and b) that my statement you quote above is very confusing.  So I'll go ahead and remove it.
